# Pre-build step: embeds web/index.html, portal.css and portal.js into
# src/web_pages.h as PROGMEM raw strings. %VER% becomes FW_VERSION.
import os

try:
    Import("env")  # noqa: F821 - provided by PlatformIO/SCons
    ROOT = env["PROJECT_DIR"]  # noqa: F821
except NameError:
    ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DELIM = "=="
ASSETS = [
    ("PAGE_HTML", "index.html"),
    ("PORTAL_CSS", "portal.css"),
    ("PORTAL_JS", "portal.js"),
]


def raw(text):
    if ")" + DELIM + '"' in text:
        raise ValueError("raw string delimiter found in web asset")
    parts = text.split("%VER%")
    q = lambda s: 'R"' + DELIM + "(" + s + ")" + DELIM + '"'
    return " FW_VERSION ".join(q(p) for p in parts)


def build():
    out = [
        "// Generated by tools/build_web.py from web/. Do not edit.",
        "#pragma once",
        "#include <Arduino.h>",
        '#include "config.h"',
        "",
    ]
    for name, fname in ASSETS:
        with open(os.path.join(ROOT, "web", fname), encoding="utf-8") as f:
            text = f.read()
        out.append("static const char %s[] PROGMEM = %s;" % (name, raw(text)))
        out.append("")
    content = "\n".join(out)
    dst = os.path.join(ROOT, "src", "web_pages.h")
    old = None
    if os.path.exists(dst):
        with open(dst, encoding="utf-8") as f:
            old = f.read()
    if old != content:  # keep mtime stable so unchanged assets do not force a rebuild
        with open(dst, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
        print("build_web: regenerated src/web_pages.h")


build()
